<?php
/**
 * Created by PhpStorm.
 * User: wangzhen
 * Date: 2016/9/27
 * Time: 16:44
 */

namespace app\components\widgets;
use app\assets\HighChartsAsset;


class HighChartsWidgets extends InputWidget
{
    /**
     * @var boolean If true, shows the widget as an inline calendar and the input as a hidden field.
     */
    public $inline = false;
    /**
     * @var array the HTML attributes for the container tag. This is only used when [[inline]] is true.
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $containerOptions = [];
    /**
     * @var string the format string to be used for formatting the date value. This option will be used
     * to populate the [[clientOptions|clientOption]] `dateFormat`.
     * The value can be one of "short", "medium", "long", or "full", which represents a preset format of different lengths.
     *
     * It can also be a custom format as specified in the [ICU manual](http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax).
     * Alternatively this can be a string prefixed with `php:` representing a format that can be recognized by the
     * PHP [date()](http://php.net/manual/de/function.date.php)-function.
     *
     * For example:
     *
     * ```php
     * 'MM/dd/yyyy' // date in ICU format
     * 'php:m/d/Y' // the same date in PHP format
     * ```
     *
     * If not set the default value will be taken from `Yii::$app->formatter->dateFormat`.
     */
    public $clientOptions;
    public function init()
    {
        if ($this->inline && !isset($this->containerOptions['id'])) {
            $this->containerOptions['id'] = $this->options['id'] . '-container';
        }
        parent::init(); // TODO: Change the autogenerated stub

    }
    public function run()
    {
        $containerID = $this->inline ? $this->containerOptions['id'] : $this->options['id'];
        $this->registerClientOptions('highcharts', $containerID);

        HighChartsAsset::register($this->getView());
    }
}