<?php

namespace app\models\classes;

use app\models\Push;
use Yii;

/**
 * This is the model class for table "cl_classes".
 *
 * @property integer $id
 * @property integer $provinceid
 * @property integer $starttime
 * @property integer $endtime
 * @property integer $createtime
 * @property integer $countyid
 * @property integer $cityid
 */
class Classes extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cl_classes';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('dbud');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['provinceid',  'createtime', 'countyid', 'cityid'], 'integer'],
            [['title','countyid', 'cityid','starttime', 'endtime'], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'provinceid' => '省',
            'starttime' => '课程开始时间',
            'endtime' => '课程结束时间',
            'createtime' => '创建时间',
            'countyid' => '区/县',
            'cityid' => '市',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert)
        {
            $this->createtime=time();
        }
        $this->starttime=strtotime($this->starttime);
        $this->endtime=strtotime($this->endtime);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
