<?php

namespace app\models\classes;

use Yii;

/**
 * This is the model class for table "cl_lesson".
 *
 * @property integer $id
 * @property integer $classesid
 * @property integer $datetime
 * @property integer $dynamicid
 * @property integer $is_push
 * @property integer $is_send
 */
class Lesson extends \yii\db\ActiveRecord
{
    public static $is_pushText=[0=>'未推送',1=>'推送中',2=>"已推送"];
    public static $is_sendText=[0=>'未发',1=>'已发'];
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cl_lesson';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('dbud');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['classesid','datetime','dynamicid'], 'required'],
            [['classesid', 'dynamicid'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'classesid' => '关联课程表ID',
            'datetime' => '日期',
            'dynamicid' => '关联内容ID',
            'is_push' =>"是否推送",
            'is_send'=>"是否发送短信"
        ];
    }
    public function beforeSave($insert)
    {
        if($insert)
        {
            $this->createtime=time();
        }
        $this->datetime=strtotime($this->datetime);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
