<?php

namespace app\models\dynamic;

use Yii;

/**
 * This is the model class for table "dc_dynamic_app".
 *
 * @property integer $id
 * @property string $title
 * @property string $ftitle
 * @property integer $dynamicid
 * @property string $url
 * @property integer $createtime
 * @property integer $level
 */
class DyApp extends \yii\db\ActiveRecord
{
    public static $levelText=[0=>"未推送",1=>"推送中",2=>"已推送"];
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dc_dynamic_app';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('dbdc');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['dynamicid', 'createtime', 'level'], 'integer'],
            [['title', 'ftitle'], 'string', 'max' => 20],
            [['url'], 'string', 'max' => 200],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '主键',
            'title' => '标题',
            'ftitle' => '副标题',
            'dynamicid' => '动态表ID',
            'url' => '链接地址',
            'createtime' => '创建时间',
            'level' => '数据状态',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert)
        {
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        $dynamic=Dynamic::findOne($this->dynamicid);
        if($dynamic)
        {
            $dynamic->delete();
        }
    }
}
