<?php

namespace app\models\dynamic;

use Yii;

/**
 * This is the model class for table "dc_dynamic_imgs".
 *
 * @property integer $id
 * @property string $src
 * @property integer $createtime
 * @property integer $dynamicid
 */
class Dyimgs extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dc_dynamic_imgs';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('dbdc');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['src', 'dynamicid'], 'required'],
            [['createtime', 'dynamicid'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'src' => '图片',
            'createtime' => '医圈发表图片的时间',
            'dynamicid' => '动态id',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert)
        {
            $this->createtime=time();
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
