<?php

namespace app\models\dynamic;

use Yii;

/**
 * This is the model class for table "dc_dynamic_open".
 *
 * @property integer $dynamicid
 * @property string $title
 * @property string $intro
 * @property integer $userid
 * @property string $video
 * @property integer $whenlong
 */
class DyOpen extends \yii\db\ActiveRecord
{
    public $subid;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dc_dynamic_open';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('dbdc');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['dynamicid','title','intro','video','whenlong'], 'required'],
            [['userid','whenlong'], 'integer'],
            [['title'], 'string', 'max' => 20],
            [['ftitle'], 'string', 'max' => 20],

            [['intro'], 'string', 'max' => 200],
            [['video'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'dynamicid' => 'Dynamicid',
            'title' => '标题',
            'ftitle' => '副标题',

            'intro' => '简介',
            'userid' => '关联专家ID',
            'video' => '视频地址',
            'pushstate' => '推送状态',
            'whenlong' =>'视频时长',
            'subid' =>  '学院'
        ];
    }
    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        $dynamic=Dynamic::findOne($this->dynamicid);
        if($dynamic)
        {
            $dynamic->delete();
        }
    }
}
