<?php

namespace app\models\doctor;

use Yii;

/**
 * This is the model class for table "user_top".
 *
 * @property integer $id
 * @property integer $userid
 * @property integer $topnum
 * @property integer $helpnum
 */
class UserTop extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_top';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('dbus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['userid', 'topnum', 'helpnum','createtime'], 'integer'],
            [['intro'], 'string', 'max' => 50],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '主键',
            'userid' => '用户ID',
            'topnum' => '排名',
            'helpnum' => '帮助人数',
            'intro'=>'简介',
            'createtime'=>'帮扶排名更新时间'
        ];
    }
    public function beforeSave($insert)
    {
        $this->createtime=time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
