<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "helping".
 *
 * @property integer $id
 * @property integer $userid
 * @property integer $toid
 * @property integer $totype
 * @property integer $createtime
 * @property integer $helptime
 */
class Helping extends \yii\db\ActiveRecord
{
    public static $toTypeText=[1=>'医生',2=>'医院'];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'helping';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('dbus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['userid', 'toid', 'totype'], 'required'],
            [['userid', 'toid', 'totype'], 'integer'],
            [['helptime'], 'string', 'max' => 20],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userid' => '主医生ID',
            'toid' => '帮扶对象ID',
            'totype' => '帮扶对象类型',
            'createtime' => '创建时间',
            'helptime' => '帮扶时间',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->createtime=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
